name: Documentation

on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Conda Environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        environment-file: docs/environment.yaml
        activate-environment: docs
        auto-activate-base: false

    - name: Install pacakge
      shell: bash -l {0}
      run: |
        pip install flake8 pytest cython numpy
        pip install .

    - name: Build docs
      shell: bash -l {0}
      run: |
        cd docs
        make html

    - name: Deploy docs
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: docs/_build/html
        CLEAN: true
        single-commit: true
